### ISSUE TITLE
 Block sealing failed                     err=unauthorized

### ISSUE THREAD

**Issue by windflowerly** [TTCECO/gttc#1]
wo deloy test private chain and run .
but display  "Block sealing failed                     err=unauthorized"

**Comment by TATAUFO** [comment]
yes, you can ignore unauthorized error. 

Is your output is combine from output of two nodes?

**Comment by wenjieme** [comment]
The output I showed is just the output of a node(node1).

**Comment by TATAUFO** [comment]
As show in the log you post, block 69 70 71 is all mined by this node. You just run one node during that time ?

**Comment by wenjieme** [comment]
Yes. They mine block alternately when I start two node.
