### ISSUE TITLE
The ttc-net-intelligence-api can't read last block

### ISSUE THREAD

**Issue by hankcocco** [TTCECO/gttc#18]
whenever pm2 start app.json, I can get the block info.
but,it can't get anything after start.
pm2 logs shows:

`0|node-app | 2020-10-23 14:58 +08:00: [eth] xx> getLatestBlock couldn't fetch block...
0|node-app | 2020-10-23 14:58 +08:00: [eth] xx> Error: invalid argument 0: hex number > 64 bits
0|node-app | 2020-10-23 14:58 +08:00:     at Object.InvalidResponse (/root/bin/www/node_modules/web3/lib/web3/errors.js:35:16)
0|node-app | 2020-10-23 14:58 +08:00:     at /root/bin/www/node_modules/web3/lib/web3/requestmanager.js:86:36
0|node-app | 2020-10-23 14:58 +08:00:     at exports.XMLHttpRequest.request.onreadystatechange (/root/bin/www/node_modules/web3/lib/web3/httpprovider.js:114:13)
0|node-app | 2020-10-23 14:58 +08:00:     at exports.XMLHttpRequest.dispatchEvent (/root/bin/www/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:591:25)
0|node-app | 2020-10-23 14:58 +08:00:     at setState (/root/bin/www/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:610:14)
0|node-app | 2020-10-23 14:58 +08:00:     at IncomingMessage.<anonymous> (/root/bin/www/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:447:13)
0|node-app | 2020-10-23 14:58 +08:00:     at IncomingMessage.emit (events.js:326:22)
0|node-app | 2020-10-23 14:58 +08:00:     at endReadableNT (_stream_readable.js:1223:12)
0|node-app | 2020-10-23 14:58 +08:00:     at processTicksAndRejections (internal/process/task_queues.js:84:21)`

**Comment by TATAUFO** [comment]
please check the config file (app.json)
it should be a list of node info like follow:

[
{
    "name"              : "your-node-name",
    "script"            : "app.js",
    "log_date_format"   : "YYYY-MM-DD HH:mm Z",
    "merge_logs"        : false,
    "watch"             : false,
    "max_restarts"      : 10,
    "exec_interpreter"  : "node",
    "exec_mode"         : "fork_mode",
    "env":
    {
      "NODE_ENV"        : "production",
      "RPC_HOST"        : "localhost",
      "RPC_PORT"        : "8501",  // rpc port 
      "LISTENING_PORT"  : "30311",
      "INSTANCE_NAME"   : "your node name",
      "CONTACT_DETAILS" : "",
      "WS_SERVER"       : "http://10.146.0.13:8888",    // report serve ip and port
      "WS_SECRET"       : "ttc",
      "VERBOSITY"       : 2
    }
  },
......
