### ISSUE TITLE
关于AlienConfig结构里面SideChain字段的疑问?

### ISSUE THREAD

**Issue by guidao-me** [TTCECO/gttc#2]
在TCC的白皮书里面看到了关于跨链的介绍，请问一下，AlienConfig里面SideChain字段代表跨链吗？但是没有看到跨链的具体结构和它的操作函数。

**Comment by TATAUFO** [comment]
AlienConfig中SideChain表示本链是否为侧链。如果为侧链，则在启动节点时需要额外的配置（具体见gttc启动参数）来设置主链的rpc地址，端口等信息，用以过去主链上为本侧链指定的当前见证人。侧链按照主链指定的顺序出块。

侧链更多的内容可见dev分支。
