### ISSUE TITLE
With -unlock option, any one can send transactions from miner without password ?

### ISSUE THREAD

**Issue by wenjieme** [TTCECO/gttc#5]
I build a test network with one miner,  and it is mining with -unlock(it is necessary) option.
And I connect to this machine using gttc attach http://xxxx:xxxx, then I can use that miner to send transaction without knowing the password, I think it is unreasonable, because the coin in the miner can be sent to anywhere without any authority, While the Ethereum's miner doesn't need to unlock.

**Comment by TATAUFO** [comment]
The default consensus of Ethereum is POW, so the miner just need to provide the proof of their work,  not need to prove their identity. (coinbase is just used for receive block reward in pow)

But in DPOS consensus, the delegate (vote by users) must seal the block in their own time period and right order which calculate by consensus, so the miner must prove who they are. The super node need to unlock the delegate address (miner) , so delegate can sign when seal the block. More details about DPOS (https://steemit.com/dpos/@dantheman/dpos-consensus-algorithm-this-missing-white-paper)
