### ISSUE TITLE
gttc如何执行

### ISSUE THREAD

**Issue by keruisiya** [TTCECO/gttc#6]
我按照文档` `HOWTO_INSTALL`安装gttc，并测试到 `build/bin/gttc --testnet` 是有结果的，但是直接执行 gttc会报错，未找到该命令，只在build/bin/gttc是可以进行相关指令的。请问我该怎么做，谢谢

**Comment by TATAUFO** [comment]
1.检查下是否编译成功，看下对应的目录下是否生成了gttc这个可执行文件。
2.检查GOPATH的路径设置。
