### ISSUE TITLE
搭建私链集群，有些节点无法挖矿，Block sealing failed  err=unauthorized

### ISSUE THREAD

**Issue by xuyao91** [TTCECO/gttc#8]
我按照 https://github.com/TTCECO/gttc/wiki/HOWTO_RUNNING_TEST_ON_PRIVATE_NETWORK 这个步骤生成了创世纪块并跑了两个节点，当我想跑第三个节点并加入网络挖矿的时候，会报如下错：
```
Block sealing failed    err=unauthorized
```
我的问题是如果节点需要拥有生成区块的权限，是不是得在创建genesis.json的时候，把该节点对应的地址加进去，就跟下面一样
```
Which accounts are vote by themselves to seal the block?(least one, those accounts will be auto pre-funded)
(The follow two address can be found in account.txt)
> 0xfa846876ef5ed3826e483303f42d987a66af8e15 
> 0x62739566c666df9a057d7e7c92898511d4e64c07
> 0x
```

**Comment by TATAUFO** [comment]
可以在创建创世块的时候将节点加进去，也可以在节点运行之后，用投票的方式选出其他的挖矿节点。

投票的方式详见 https://github.com/TTCECO/gttc/wiki//HOWTO_VOTE_ON_GTTC

**Comment by xuyao91** [comment]
好的，我明白了，谢谢
